"use client";

import { useState } from "react";
import { Share2 } from "lucide-react";

/**
 * Shareable results (audit Fix 8). Generates a branded, good-looking activation
 * summary the user can print or save as PDF and hand to a teammate/client.
 *
 * Intentionally a LOCAL export — it does not publish anything or create a public
 * link. Per the brief, any public/private link sharing must be an explicit,
 * user-controlled setting; nothing here defaults to public.
 */
type ShareData = {
  workspace: { name: string };
  users: { stage: string; is_anonymous: boolean }[];
  totals: { users: number; pageViews: number; totalClicks: number };
};

const ACTIVATED = new Set(["active", "conversion_ready", "paid"]);

export function ShareResultsButton({ data }: { data: ShareData }) {
  const [busy, setBusy] = useState(false);

  function exportSummary() {
    setBusy(true);
    try {
      const signups = data.users.filter((u) => !u.is_anonymous);
      const n = signups.length || 1;
      const activated = signups.filter((u) => ACTIVATED.has(u.stage)).length;
      const ready = signups.filter((u) => u.stage === "conversion_ready" || u.stage === "paid").length;
      const paid = signups.filter((u) => u.stage === "paid").length;
      const pct = (x: number) => Math.round((x / n) * 100);
      const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

      const row = (label: string, count: number, color: string) => `
        <tr>
          <td style="padding:10px 0;color:#3c4250;font-weight:600">${label}</td>
          <td style="padding:10px 0;text-align:right;font-variant-numeric:tabular-nums;font-weight:700;color:#0b0d12">${count}</td>
          <td style="padding:10px 0 10px 16px;width:55%">
            <div style="background:#eef2f7;border-radius:6px;height:14px;overflow:hidden">
              <div style="background:${color};height:14px;width:${Math.max(pct(count), 3)}%"></div>
            </div>
          </td>
          <td style="padding:10px 0 10px 12px;text-align:right;color:#6b7280;font-weight:600;font-variant-numeric:tabular-nums">${pct(count)}%</td>
        </tr>`;

      const html = `<!doctype html><html><head><meta charset="utf-8">
      <title>${data.workspace.name} — Activation snapshot</title>
      <style>
        *{box-sizing:border-box} body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;margin:0;background:#f4f6fb;color:#0b0d12}
        .sheet{max-width:680px;margin:32px auto;background:#fff;border:1px solid #e6ebf1;border-radius:14px;overflow:hidden}
        .top{background:linear-gradient(135deg,#1557c9,#0b3a5e);color:#fff;padding:22px 28px}
        .brand{display:flex;align-items:center;gap:8px;font-weight:700;font-size:14px;letter-spacing:.02em}
        .dot{width:10px;height:10px;border-radius:50%;background:#fff}
        .body{padding:26px 28px}
        h1{font-size:20px;margin:0 0 2px} .sub{color:#6b7280;font-size:13px;margin:0 0 22px}
        .hero{display:flex;gap:14px;margin-bottom:24px}
        .stat{flex:1;background:#f7fafd;border:1px solid #e6ebf1;border-radius:10px;padding:14px 16px}
        .stat .v{font-size:24px;font-weight:800;color:#0b3a5e} .stat .l{font-size:12px;color:#6b7280;font-weight:600}
        table{width:100%;border-collapse:collapse;font-size:14px}
        .foot{padding:16px 28px;border-top:1px solid #eef2f7;color:#9aa1ad;font-size:12px;display:flex;justify-content:space-between}
        @media print{body{background:#fff}.sheet{border:none;margin:0}}
      </style></head><body>
        <div class="sheet">
          <div class="top"><div class="brand"><span class="dot"></span> ConversionCRM</div></div>
          <div class="body">
            <h1>${data.workspace.name} — Activation snapshot</h1>
            <p class="sub">${date}</p>
            <div class="hero">
              <div class="stat"><div class="v">${pct(activated)}%</div><div class="l">Activation rate</div></div>
              <div class="stat"><div class="v">${signups.length}</div><div class="l">Identified signups</div></div>
              <div class="stat"><div class="v">${paid}</div><div class="l">Paid</div></div>
            </div>
            <table>
              ${row("Signups", signups.length, "#bcd6fb")}
              ${row("Activated", activated, "#4d9af5")}
              ${row("Conversion-ready", ready, "#1557c9")}
              ${row("Paid", paid, "#0b3a5e")}
            </table>
          </div>
          <div class="foot"><span>Generated by ConversionCRM</span><span>conversioncrm.co</span></div>
        </div>
        <script>window.onload=function(){setTimeout(function(){window.print()},300)}<\/script>
      </body></html>`;

      const w = window.open("", "_blank", "width=760,height=900");
      if (!w) {
        alert("Allow pop-ups to export your activation summary.");
        return;
      }
      w.document.open();
      w.document.write(html);
      w.document.close();
    } finally {
      setBusy(false);
    }
  }

  return (
    <button
      type="button"
      onClick={exportSummary}
      disabled={busy}
      className="inline-flex items-center gap-1.5 rounded-lg bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 shadow-soft transition-colors hover:bg-gray-50 disabled:opacity-60"
      title="Export a branded activation summary (PDF) to share with your team"
    >
      <Share2 className="h-3.5 w-3.5" /> Export summary
    </button>
  );
}
